name: Build LLVM from Source

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build LLVM on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-24.04]
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build unzip curl wget python3 git
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          fi

      - name: Set Environment Variables
        run: |
          echo "Setting up environment variables..."
          echo "MajorLLVMVer=16" >> $GITHUB_ENV
          echo "LLVMVer=16.0.4" >> $GITHUB_ENV
          echo "LLVMHome=llvm-${MajorLLVMVer}.0.0.obj" >> $GITHUB_ENV
          echo "SourceLLVM=https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${LLVMVer}.zip" >> $GITHUB_ENV
          echo "SVFHOME=$PWD" >> $GITHUB_ENV
          echo "jobs=$(nproc)" >> $GITHUB_ENV

      - name: Download and Extract LLVM
        run: |
          set -e
          echo "Downloading LLVM source..."
          if [[ ! -f "llvm.zip" ]]; then
              curl -L --retry 5 --retry-delay 5 "$SourceLLVM" -o llvm.zip || wget -c "$SourceLLVM" -O llvm.zip
          fi

          # 下载失败就报错
          if [[ ! -s llvm.zip ]]; then
              echo "Error: llvm.zip download failed or is empty!"
              ls -l llvm.zip
              exit 1
          fi

          echo "Extracting LLVM source (silent mode)..."
          rm -rf llvm-source
          mkdir llvm-source
          unzip -q llvm.zip -d llvm-source || { echo "Error: Failed to unzip LLVM!"; exit 1; }

          echo "Finding LLVM source directory..."
          LLVM_SRC_DIR=$(find llvm-source -maxdepth 1 -type d -name "llvm-project-*")
          if [[ -z "$LLVM_SRC_DIR" ]]; then
              echo "Error: LLVM source directory not found!"
              ls -R llvm-source
              exit 1
          fi

          EXPECTED_DIR="llvm-source/llvm-project-${LLVMVer}"
          if [[ "$LLVM_SRC_DIR" != "$EXPECTED_DIR" ]]; then
              echo "Renaming LLVM source directory..."
              mv "$LLVM_SRC_DIR" "$EXPECTED_DIR"
          fi

          if [[ ! -d "$EXPECTED_DIR/llvm" ]]; then
              echo "Error: LLVM source directory '$EXPECTED_DIR/llvm' not found!"
              ls -R "$EXPECTED_DIR"
              exit 1
          fi

          echo "LLVM source directory is ready: $EXPECTED_DIR"

      - name: Build LLVM
        run: |
          set -e
          EXPECTED_DIR="$PWD/llvm-source/llvm-project-${LLVMVer}"

          echo "Building LLVM..."
          mkdir -p llvm-build
          cd llvm-build
          
          if [[ ! -d "$EXPECTED_DIR/llvm" ]]; then
              echo "FATAL ERROR: LLVM source directory '$EXPECTED_DIR/llvm' not found!"
              ls -R "$EXPECTED_DIR"
              exit 1
          fi

          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="$SVFHOME/$LLVMHome" \
                -DLLVM_ENABLE_PROJECTS="clang" \
                -DLLVM_ENABLE_RTTI=ON \
                -DBUILD_SHARED_LIBS=ON \
                -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
                "$EXPECTED_DIR/llvm"
          cmake --build . --parallel ${jobs}
          cmake --install .

          cd ..
          rm -rf llvm.zip llvm-source llvm-build

      - name: Package LLVM
        run: |
          echo "Packaging LLVM..."
          OS_VERSION=$(lsb_release -rs)
          ARCH=${{ matrix.arch }}
          ZIP_NAME="llvm-16-ubuntu${OS_VERSION}-${ARCH}.zip"
          mv llvm-16.0.0.obj llvm-16
          zip -r $ZIP_NAME llvm-16
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload LLVM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}
          retention-days: 7
