name: Build LLVM on Ubuntu 24.04 ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LLVM
        run: |
          # 你的编译命令
          make llvm-install
          tar -czf llvm-install-arm64.tar.gz llvm-install

      - name: Upload LLVM artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-install-arm64
          path: llvm-install-arm64.tar.gz
