name: Build LLVM with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build LLVM on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build LLVM using Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/${{ matrix.arch }}
          tags: llvm-build:${{ matrix.arch }}

      - name: Extract LLVM Build Output
        run: |
          docker create --name llvm-container llvm-build:${{ matrix.arch }}
          docker cp llvm-container:/output llvm-16-${{ matrix.arch }}
          docker rm llvm-container
          zip -r llvm-16-${{ matrix.arch }}.zip llvm-16-${{ matrix.arch }}

      - name: Upload LLVM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-16-${{ matrix.arch }}.zip
          path: llvm-16-${{ matrix.arch }}.zip
          retention-days: 7
