name: Build LLVM on Ubuntu 24.04 ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload-existing-artifact:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Locate Existing Artifact
        run: |
          echo "Checking if llvm-install-arm64.tar.gz exists..."
          ls -lh $GITHUB_WORKSPACE || true
          ls -lh $GITHUB_WORKSPACE/llvm-install-arm64.tar.gz || true

      - name: Upload Artifact (if exists)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: llvm-install-arm64
          path: $GITHUB_WORKSPACE/llvm-install-arm64.tar.gz
