name: Build LLVM on Windows

on:
  push:
    branches: [ llvm-16-windows ]

jobs:
  build-llvm:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install ninja --yes
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Clone LLVM source
      run: |
        git clone --depth=1 https://github.com/llvm/llvm-project.git
        dir llvm-project

    - name: Configure LLVM with CMake
      run: |
        mkdir llvm-build
        cd llvm-build
        cmake ../llvm-project/llvm `
          -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DLLVM_ENABLE_PROJECTS="clang" `
          -DLLVM_TARGETS_TO_BUILD=host `
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\llvm-install" `
          -DLLVM_ENABLE_ASSERTIONS=ON

    - name: Build and install LLVM
      run: |
        cd llvm-build
        cmake --build . --target install

    - name: Verify llvm-config.cmake exists
      run: |
        if (Test-Path "${{ github.workspace }}\llvm-install\lib\cmake\llvm\llvm-config.cmake") {
          Write-Host "✅ llvm-config.cmake was generated."
        } else {
          Write-Error "❌ llvm-config.cmake was not found."
          exit 1
        }

    - name: Upload LLVM build artifact
      uses: actions/upload-artifact@v4
      with:
        name: llvm-windows-build
        path: ${{ github.workspace }}\llvm-install
